module mainfiles{
    interface Hangman {
        boolean start(in string name);
        string guessedWord(in string name);
        short play(in string name, in char guess, in short index);
        boolean inPlay(in string name);
        oneway void shutdown();
    };
};