package mainfiles;


/**
* mainfiles/HangmanOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from mainfiles.idl
* Monday, April 30, 2018 4:03:35 PM PHT
*/

public interface HangmanOperations 
{
  boolean start (String name);
  String guessedWord (String name);
  short play (String name, char guess, short index);
  boolean inPlay (String name);
  void shutdown ();
} // interface HangmanOperations
