package mainfiles;


/**
* mainfiles/Hangman.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from mainfiles.idl
* Monday, April 30, 2018 4:03:35 PM PHT
*/

public interface Hangman extends HangmanOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hangman
